DjangoBlog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/',include('blog.urls',namespace='blog',app_name='blog')),
]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.post_list,name='post_list'),
    # url(r'^$',views.PostListView.as_view(),name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',views.post_detail,name='post_dateil'),
    url(r'^(?P<post_id>\d+)/share/$',views.post_share,name='post_share'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$',views.post_list,name='post_list_by_tag'),    #标签相关
    ]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager     #第三方标签库

# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft','草稿'),
        ('published','发布'),
    )
    title = models.CharField(max_length=200)    #标题
    slug = models.SlugField(max_length=250,unique_for_date='publish')   #在URLS中使用，一个短标签
    author = models.ForeignKey(User,related_name='blog_posts')  #作者
    body = models.TextField()   #文章
    publish = models.DateTimeField(default=timezone.now)    #发布时间
    created = models.DateTimeField(auto_now_add=True)   #创建时间
    updated = models.DateTimeField(auto_now=True)   #更新时间
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft') #展示状态
    tags = TaggableManager()    #第三方标签库

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):     #使用名字和可选参数构建URLs
        return reverse('blog:post_dateil',args=[self.publish.year,
                                                self.publish.strftime('%m'),
                                                self.publish.strftime('%d'),
                                                self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)  #评论是否显示

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} to on {}'.format(self.name,self.post)

blog/forms.py
# -*- coding: utf-8 -*-
# @Time    : 2017/5/2 22:40
# @Author  : yj

from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment     #以Comment来生成表单
        fields = ('name','email','body')    #表明只有哪些字段显示在表单中

blog/views.py
from django.shortcuts import render,get_object_or_404
from django.core.mail import send_mail
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.db.models import Count
from django.views.generic import ListView
from .forms import EmailPostForm,CommentForm
from .models import Post,Comment
from taggit.models import Tag

# Create your views here.

# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'


def post_list(request,tag_slug=None): #列表
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag,slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list,3)    #每页显示3条
    page = request.GET.get('page')  #指明当前页数
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)    #如果页面不是一个整数交付第一页
    except EmptyPage:
        posts = paginator.page(paginator.num_pages) #如果页面范围交付最后一页的搜索结果
    return render(request,'blog/post/list.html',{'posts':posts,'page':page,'tag':tag})


def post_detail(request,year,month,day,post):   #详情
    post = get_object_or_404(Post,slug=post,status='published',publish__year=year,publish__month=month,publish__day=day)
    #此帖子的活动评论列表
    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method =='POST':
        #发表了评论
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            #创建评论对象，但不保存到数据库
            new_comment = comment_form.save(commit=False)
            #将当前帖子分配给评论
            new_comment.post = post
            #将评论保存到数据库
            new_comment.save()
    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id',flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    return render(request,'blog/post/detail.html',{'post':post,
                                                   'comments':comments,
                                                   'new_comment':new_comment,
                                                   'comment_form':comment_form,
                                                   'similar_posts':similar_posts})


def post_share(request,post_id):
    post = get_object_or_404(Post,id=post_id,status = 'published')  #检索post的id
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{}({}) 建议你阅读 "{}"'.format(cd['name'],cd['email'],post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: "{}"'.format(post.title,post_url,cd['name'],cd['comments'])
            send_mail(subject, message, '809127232@qq.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request,'blog/post/share.html',{'post':post,'form':form,'sent':sent})

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>My blog</h2>
            <p>This my blog</p>
    </div>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|linebreaks }}
    <p><a href="{% url 'blog:post_share' post.id %}">分享这篇文章</a></p>

    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} comment {{ total_comments|pluralize }}</h2>
    {% endwith %}
    <h2>类似的文章</h2>
    {% for post in similar_posts %}

        <p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a> </p>
        {% empty %}
        没有类似的帖子
    {% endfor %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                评论{{ forloop.counter }} by{{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>目前没有评论</p>
    {% endfor %}

    {% if new_comment %}

        <h2>您的评论已添加</h2>
    {% else %}
        <h2>添加新评论</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="添加评论"></p>
        </form>
    {% endif %}
{% endblock %}

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% block title %}My Blog {% endblock %}

{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
        <h2>帖子标记为:"{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        <p class="tags">标签:{% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
            {% if not forloop.last %},{% endif %}
            {% endfor %}</p>

        <p class="date">
            发布日期 {{ post.publish }} &nbsp&nbsp作者 {{ post.author }}
        </p>
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}
    {% include 'pagination.html' with page=posts %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% block title %} Share a pos {% endblock %}

{% block content %}

    {% if sent %}

        <h1>电子邮件已成功发送</h1>
        <p>"{{ post.title }}" 被成功送到 {{ cd.to }}.</p>
        {% else %}
        <h1>Share "{{ post.title }}" by e-email</h1>
        <form action="" method="post">
            {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}

blog/templates/pagination.html
<div class='pagination'>
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">上一页</a>
        {% endif %}
        <span class="curren t">
      第 {{ page.number }}页/共 {{ page.paginator.num_pages }}页
    </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">下一页</a>
        {% endif %}
    </span>
</div>